version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: myAdmin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - 6379:6379
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: mongodb://myAdmin:1234@mongo:27017/?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: report-type-values-analytics
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: 1234
      SPRING_CACHE_TYPE: redis
      JWT_SECRET: qwertyuiop1234567890qwertyuiop1234567890qwertyuiop
    ports:
      - 8088:8080
    depends_on:
      - mongo
      - redis
    volumes:
      - ./src/main/resources:/app/resources
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
    driver: bridge


